- [ ] [[../todo|todo]] [[../kubectl|kubectl]] [[../kubernetes|kubernetes]]
  ```sh 
  E0307 23:44:59.190224   47471 portforward.go:409] an error occurred forwarding 3000 -> 3000: error forwarding port 3000 to pod d65e37a0e11100ea7a5ec4165f518eb5a72e58055fbab37ca81b78534054edc8, uid : failed to execute portforward in network namespace "/var/run/netns/cni-7491da70-324f-ff85-159a-2e01ad37d3f1": failed to connect to localhost:3000 inside namespace "d65e37a0e11100ea7a5ec4165f518eb5a72e58055fbab37ca81b78534054edc8", IPv4: dial tcp4 127.0.0.1:3000: connect: connection refused IPv6 dial tcp6: address localhost: no suitable address found
  ```
  - ingressroute > svc > dp > pod 까지 잘 연결되서 외부 연결됨
  - 로컬에서 portforward 를 하면 위 에러가 발생
    ```sh 
    Client Version: v1.29.1
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    Server Version: v1.27.6
    ```
